# Site Settings
title: My Resume
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Ena Urbina
tagline: Course Developer Student Assistant
pic: photo1.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'My name is Ena and I am a Course Developer for Florida International University Online. My
work requires a great deal time management, creativity and attention to detail.'

#sidebar links
email: eurbi012@fiu.edu
phone: 786 227 4008
linkedin: enaurbina
github: eurbi012
twitter: '@ena_urbina'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
